---
variables:
  HOMEBREW_NO_AUTO_UPDATE: 1

stages:
  - all

Run workflow:
  parallel:
    matrix:
      - RUNNER_TAG: saas-linux-small-amd64
        IMAGE:
          - debian:trixie-20240110
          - rockylinux/rockylinux:9.3.20231119-ubi
      - RUNNER_TAG: saas-macos-medium-m1
        IMAGE:
          - macos-12-xcode-14
          - macos-13-xcode-14
          - macos-14-xcode-15
  tags:
    - ${RUNNER_TAG}
  image: ${IMAGE}
  stage: all
  script: |
    set -x
    git clone https://github.com/spack/spack.git
    export PATH="${PWD}/spack/bin:${PATH}"
    eval "$(spack env activate --sh .)"
    spack mirror add \
        --unsigned \
        --oci-username ${CI_REGISTRY_USER} \
        --oci-password ${CI_REGISTRY_PASSWORD} \
        gitlab-container-registry \
        oci://${CI_REGISTRY_IMAGE}
    ./install.sh gitlab-container-registry | tee install.log
    ./my_view/bin/python -c 'print("hello world")'
  artifacts:
    when: always
    paths:
      - install.log
