---
variables:
  HOMEBREW_NO_AUTO_UPDATE: 1

stages:
  - all

Run workflow:
  stage: all
  script: |
    git clone https://github.com/spack/spack.git
    export PATH="${PWD}/spack/bin:${PATH}"
    eval "$(spack env activate --sh .)"
    spack mirror add \
        --unsigned
        --oci-username ${CI_REGISTRY_USER} \
        --oci-password ${CI_REGISTRY_PASSWORD} \
        gitlab-container-registry \
        oci://${CI_REGISTRY_IMAGE}
    ./install.sh gitlab-container-registry
    ./my_view/bin/python -c 'print("hello world")'
