---
name: Build

on: push

jobs:
  example:
    name: os:${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Spack
        uses: spack/setup-spack@v2
      - name: Concretize
        run: spack -e . concretize
      - name: Install
        run: spack -e . install --no-check-signature
      - name: Push packages and update index
        run: |
          spack -e . \
            mirror set \
            --push \
            --oci-username ${{ github.actor }} \
            --oci-password "${{ secrets.GITHUB_TOKEN }}" \
            local-buildcache
          spack -e . \
            buildcache push \
            --unsigned \
            --update-index \
            local-buildcache
        if: ${{ !cancelled() }}
      - name: Run
        run: |
          ./my_view/bin/python -c 'print("hello world")'
