---
name: Build

on: push

jobs:
  example:
    name: os:${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-12
          - macos-13
          - macos-14
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Spack
      #   uses: spack/setup-spack@v2
      - name: Checkout Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
      - name: Add Spack to PATH
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
      - name: Concretize
        run: spack -e . concretize
      - name: Install
        run: spack -e . install --no-check-signature
      - name: Push packages and update index
        run: |
          spack -e . \
            mirror set \
            --push \
            --oci-username ${{ github.actor }} \
            --oci-password "${{ secrets.GITHUB_TOKEN }}" \
            local-buildcache
          spack -e . \
            buildcache push \
            --unsigned \
            --update-index \
            local-buildcache
        if: ${{ !cancelled() }}
      - name: Run
        run: |
          ./my_view/bin/python -c 'print("hello world")'
