---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  schedule:
    # 0215 daily
    - cron: '15 2 * * *'

jobs:
  example:
    name: os:${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-12
          - macos-13
          - macos-14
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Clone Spack
        uses: actions/checkout@v4
        with:
          repository: spack/spack
          path: spack
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Print Spack configuration
        run: |
          spack config blame config
          spack debug report
      - name: Set credentials for mirror
        run: |
          eval "$(spack env activate --sh .)"
          spack mirror set \
              --oci-username ${{ github.actor }} \
              --oci-password "${{ secrets.GITHUB_TOKEN }}" \
              "${mirror_name}"
      - name: Install packages into environment and push to buildcache
        run: |
          eval "$(spack env activate --sh .)"
          bash ./install.sh "${mirror_name}"
      - name: Run
        run: |
          ./my_view/bin/python -c 'print("hello world")'
